### ISSUE TITLE
Rework editor modes: reduce to two modes

### ISSUE THREAD

**Issue by xJREB** [adr/adr-manager#121]
Basic mode and professional mode

**Comment by danielabajirov** [comment]
Advanced mode has been removed from the editor modes. I tested it manually and it doesn't seem to be a problem with the functionality of the tool. The changes can be found in the TwoModes#121 branch. If everything is in order, I can make a pull request.
 The E2E fail at the moment because of the account used as authentication ID. I think the E2E should be revised and improved or changed (I don't know how important they are for this contest).

**Comment by xJREB** [comment]
I have a look at it for potential improvements. Concerning the failing of the e2e test suite: are you referring to the `authId` in `cypress/integration/adrManagerTest/constants.js`? To which account does this token belong?

**Comment by danielabajirov** [comment]
Yes, that is correct. The `authId` refers to a test account that we created for testing purposes.

**Comment by xJREB** [comment]
OK, understood. For the CI, this should probably be moved to an ENV variable which comes from GitHub Actions (https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_). And locally, developers can overwrite it with a `cypress.env.json` file (https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypress-env-json). I create an issue for this. 

Concerning the two modes, I briefly tested them locally and liked them very much. Seems cleaner than the initial 3. Running the e2e suite with them would probably be a good idea before merging this, though. :D

**Comment by xJREB** [comment]
The e2e test reworking has been merged, so please go ahead with the pull request. :)

**Comment by xJREB** [comment]
Implemented with #126
